AdvancePhonebook/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdvancePhonebook.Data;
using AdvancePhonebook.Models;

namespace AdvancePhonebook.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contacts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Contacts.Include(c => c.Enterprise);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacts = await _context.Contacts
                .Include(c => c.Enterprise)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contacts == null)
            {
                return NotFound();
            }

            return View(contacts);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {
            ViewData["EnterpriseId"] = new SelectList(_context.Set<Enterprises>(), "Id", "Name");
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,EnterpriseId,Role,Email,PhoneNumber,Line,CellPhone,Fax,Address,CreatedAt,UpdatedAt")] Contacts contacts)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contacts);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EnterpriseId"] = new SelectList(_context.Set<Enterprises>(), "Id", "Name", contacts.EnterpriseId);
            return View(contacts);
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacts = await _context.Contacts.FindAsync(id);
            if (contacts == null)
            {
                return NotFound();
            }
            ViewData["EnterpriseId"] = new SelectList(_context.Set<Enterprises>(), "Id", "Name", contacts.EnterpriseId);
            return View(contacts);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,EnterpriseId,Role,Email,PhoneNumber,Line,CellPhone,Fax,Address,CreatedAt,UpdatedAt")] Contacts contacts)
        {
            if (id != contacts.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contacts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactsExists(contacts.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EnterpriseId"] = new SelectList(_context.Set<Enterprises>(), "Id", "Name", contacts.EnterpriseId);
            return View(contacts);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacts = await _context.Contacts
                .Include(c => c.Enterprise)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contacts == null)
            {
                return NotFound();
            }

            return View(contacts);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var contacts = await _context.Contacts.FindAsync(id);
            _context.Contacts.Remove(contacts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(string name)
        {
            ViewData["Title"] = "جستجوی مخاطب برای " + name;

            if (name == null)
            {
                return NotFound();
            }

            var result =  _context.Contacts
                .Include(c => c.Enterprise)
                .OrderBy(h=>h.CreatedAt)
                .Where(n=>n.Name.Contains(name))
                .ToArray();
            

            if (result == null)
            {
                return Redirect("/Contacts");
            }


            return View(result);
        }

        private bool ContactsExists(long id)
        {
            return _context.Contacts.Any(e => e.Id == id);
        }
    }
}

AdvancePhonebook/Controllers/DescriptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdvancePhonebook.Data;
using AdvancePhonebook.Models;

namespace AdvancePhonebook.Controllers
{
    public class DescriptionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DescriptionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Descriptions
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Descriptions.Include(d => d.Contact);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Descriptions/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var descriptions = await _context.Descriptions
                .Include(d => d.Contact)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (descriptions == null)
            {
                return NotFound();
            }

            return View(descriptions);
        }

        // GET: Descriptions/Create
        public IActionResult Create()
        {
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Name");
            return View();
        }

        // POST: Descriptions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Topic,ContactId,Description,CreatedAt,UpdatedAt")] Descriptions descriptions)
        {
            if (ModelState.IsValid)
            {
                _context.Add(descriptions);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Name", descriptions.ContactId);
            return View(descriptions);
        }

        // GET: Descriptions/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var descriptions = await _context.Descriptions.FindAsync(id);
            if (descriptions == null)
            {
                return NotFound();
            }
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Name", descriptions.ContactId);
            return View(descriptions);
        }

        // POST: Descriptions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Topic,ContactId,Description,CreatedAt,UpdatedAt")] Descriptions descriptions)
        {
            if (id != descriptions.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(descriptions);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DescriptionsExists(descriptions.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Name", descriptions.ContactId);
            return View(descriptions);
        }

        // GET: Descriptions/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var descriptions = await _context.Descriptions
                .Include(d => d.Contact)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (descriptions == null)
            {
                return NotFound();
            }

            return View(descriptions);
        }

        // POST: Descriptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var descriptions = await _context.Descriptions.FindAsync(id);
            _context.Descriptions.Remove(descriptions);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DescriptionsExists(long id)
        {
            return _context.Descriptions.Any(e => e.Id == id);
        }
    }
}

AdvancePhonebook/Controllers/EnterprisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdvancePhonebook.Data;
using AdvancePhonebook.Models;

namespace AdvancePhonebook.Controllers
{
    public class EnterprisesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EnterprisesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Enterprises
        public async Task<IActionResult> Index()
        {
            return View(await _context.Enterprises.ToListAsync());
        }

        // GET: Enterprises/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enterprises = await _context.Enterprises
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enterprises == null)
            {
                return NotFound();
            }

            return View(enterprises);
        }

        // GET: Enterprises/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Enterprises/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,PhoneNumber,Fax,Address,PostalCode,CreatedAt,UpdatedAt")] Enterprises enterprises)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enterprises);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(enterprises);
        }

        // GET: Enterprises/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enterprises = await _context.Enterprises.FindAsync(id);
            if (enterprises == null)
            {
                return NotFound();
            }
            return View(enterprises);
        }

        // POST: Enterprises/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,Email,PhoneNumber,Fax,Address,PostalCode,CreatedAt,UpdatedAt")] Enterprises enterprises)
        {
            if (id != enterprises.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enterprises);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnterprisesExists(enterprises.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(enterprises);
        }

        // GET: Enterprises/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enterprises = await _context.Enterprises
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enterprises == null)
            {
                return NotFound();
            }

            return View(enterprises);
        }

        // POST: Enterprises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var enterprises = await _context.Enterprises.FindAsync(id);
            _context.Enterprises.Remove(enterprises);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnterprisesExists(long id)
        {
            return _context.Enterprises.Any(e => e.Id == id);
        }
    }
}

AdvancePhonebook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Slim">
    <meta name="twitter:description" content="Premium Quality and Responsive UI for Dashboard.">
    <meta name="twitter:image" content="http://themepixels.me/slim/img/slim-social.png">

    <!-- Facebook -->
    <meta property="og:url" content="http://themepixels.me/slim">
    <meta property="og:title" content="Slim">
    <meta property="og:description" content="Premium Quality and Responsive UI for Dashboard.">

    <meta property="og:image" content="http://themepixels.me/slim/img/slim-social.png">
    <meta property="og:image:secure_url" content="http://themepixels.me/slim/img/slim-social.png">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="600">

    <!-- Meta -->
    <meta name="description" content="Premium Quality and Responsive UI for Dashboard.">
    <meta name="author" content="ThemePixels">

    <title>@ViewData["Title"] - دفترچه تلفن</title>

    <!-- vendor css -->
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/lib/Ionicons/css/ionicons.css" rel="stylesheet">
    <link href="~/lib/chartist/css/chartist.css" rel="stylesheet">
    <link href="~/lib/rickshaw/css/rickshaw.min.css" rel="stylesheet">

    <!-- Slim CSS -->
    <link rel="stylesheet" href="~/css/slim.css">

    <!-- Slim CSS -->
    <link rel="stylesheet" href="~/css/custom.css">

</head>
<body>
    <div class="slim-header persian">
        <div class="container">
            <div class="slim-header-left">
                <h2 class="slim-logo">
                    <a href="/">
                        دفترچه تلفن پیشرفته
                    </a>
                </h2>
                <form asp-controller="Contacts" asp-action="Search" method="post">
                    <div class="search-box">
                        <input type="text" name="name" class="form-control" placeholder="جستجو ...">
                        <button class="btn btn-primary">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div><!-- slim-header-left -->
        @*<div class="slim-header-right">
            <partial name="_LoginPartial" />
        </div><!-- header-right -->*@
    </div><!-- container -->

    <div class="slim-navbar persian">
        <div class="container">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Descriptions" asp-action="Index" title="توضیحات">
                        <i class="icon ion-android-archive"></i><span>توضیحات</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Contacts" asp-action="Index" title="مخاطبین">
                        <i class="icon ion-android-phone-portrait"></i><span>مخاطبین</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Enterprises" asp-action="Index" title="شرکت ها">
                        <i class="icon ion-android-document"></i><span>شرکت ها</span>
                    </a>
                </li>
            </ul>
        </div><!-- container -->
    </div><!-- slim-navbar -->

    <div class="slim-mainpanel">
        <div class="container">

            @RenderBody()

        </div><!-- container -->
    </div><!-- slim-mainpanel -->

    <div class="slim-footer">
        <div class="container">
            <p> &copy; 1399 - Milad Xandi</p>
            <p>Designed by: <a href="">ThemePixels</a></p>
        </div><!-- container -->
    </div><!-- slim-footer -->


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/popper.js/js/popper.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jquery.cookie/js/jquery.cookie.js"></script>
    <script src="~/lib/chartist/js/chartist.js"></script>
    <script src="~/lib/d3/js/d3.js"></script>
    <script src="~/lib/rickshaw/js/rickshaw.min.js"></script>
    <script src="~/lib/jquery.sparkline.bower/js/jquery.sparkline.min.js"></script>
    <script src="~/js/ResizeSensor.js"></script>
    <script src="~/js/dashboard.js"></script>
    <script src="~/js/slim.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>